// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7TCbmb0w19ypngkYrjzxdj63dv-9fdTk',
    appId: '1:650193761776:web:1ac58b4b638176ceaa5935',
    messagingSenderId: '650193761776',
    projectId: 'message-board-87d3a',
    authDomain: 'message-board-87d3a.firebaseapp.com',
    storageBucket: 'message-board-87d3a.firebasestorage.app',
    measurementId: 'G-TYCWM2P3QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdrdczD0MOdu1uDDpNoD4sC8FEyHQRy70',
    appId: '1:650193761776:android:d9b9334561205262aa5935',
    messagingSenderId: '650193761776',
    projectId: 'message-board-87d3a',
    storageBucket: 'message-board-87d3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMtFhwFBdmmo34F5ahv2nl4MKXeaTYBw',
    appId: '1:650193761776:ios:814ffc70e615418faa5935',
    messagingSenderId: '650193761776',
    projectId: 'message-board-87d3a',
    storageBucket: 'message-board-87d3a.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbMtFhwFBdmmo34F5ahv2nl4MKXeaTYBw',
    appId: '1:650193761776:ios:814ffc70e615418faa5935',
    messagingSenderId: '650193761776',
    projectId: 'message-board-87d3a',
    storageBucket: 'message-board-87d3a.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7TCbmb0w19ypngkYrjzxdj63dv-9fdTk',
    appId: '1:650193761776:web:926eae59249ad65eaa5935',
    messagingSenderId: '650193761776',
    projectId: 'message-board-87d3a',
    authDomain: 'message-board-87d3a.firebaseapp.com',
    storageBucket: 'message-board-87d3a.firebasestorage.app',
    measurementId: 'G-KN1QDDPK4E',
  );
}
